on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[release]')"
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: '6.21.0'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: '6.21.0'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: pnpm
      - run: pnpm install
      - run: pnpm test

  version-major:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[major]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: '6.21.0'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: pnpm
      - run: git config --global user.name github-actions
      - run: git config --global user.email github-actions@github.com
      - run: "pnpm version major -m '[release] %s'"
      - run: git push --follow-tags

  version-minor:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[minor]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: '6.21.0'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: pnpm
      - run: git config --global user.name github-actions
      - run: git config --global user.email github-actions@github.com
      - run: "pnpm version minor -m '[release] %s'"
      - run: git push --follow-tags

  version-patch:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[patch]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: '6.21.0'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: pnpm
      - run: git config --global user.name github-actions
      - run: git config --global user.email github-actions@github.com
      - run: "pnpm version patch -m '[release] %s'"
      - run: git push --follow-tags